# Generated by Django 3.1.7 on 2021-12-03 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('cat', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('fab', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('ver', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=9, null=True)),
                ('price', models.IntegerField(default=0)),
                ('critic', models.IntegerField(default=1)),
                ('stock', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('origen', models.CharField(blank=True, max_length=50, null=True)),
                ('nota', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
